### ISSUE TITLE
저희 벌금 5000원 하기로 하지 않았나요?

### ISSUE THREAD

**Issue by greenn-lab** [jpa-study/jpa#1]
크게 위화감 있는건 아닌데...
아까 미팅하면서 5000원으로 하자 했던것 같아서요.
아니면 그냥 close 시켜도 될 것 같아요;;;
(이런거 이슈로 써도 되는건가 싶으면서... 우리 메신저 단톡방도 있는데^^;;;)

**Comment by junhee-ko** [comment]
아아 제 실수네요 ㅠㅠ 
수정해서 다시 Push 하겠습니다~

**Comment by greenn-lab** [comment]
스터디 잘 되도록 이것 저것 챙기시는데, 제가 귀찮게 하는 건가 싶기도 하네요.
그런데도 바로 반영해 주시고. 감사합니다👍
